FROM amazoncorretto:11
MAINTAINER Miguel_Alejandro_Barconte
COPY target/api-rest-ejemplo-curso-0.0.1-SNAPSHOT.jar api-rest-ejemplo-curso-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/api-rest-ejemplo-curso-0.0.1-SNAPSHOT.jar"]